<h1><center>Assignment 1</center></h1>

# Initializations

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import label_binarize

def load_hugin_dataset(filename, target_feature):
    """Load a dataset simulated from a Hugin file."""
    df=pd.read_csv(filename)
    y=np.asarray(df[target_feature].values, dtype=str)
    X=df.loc[:, df.columns != target_feature].values
    feature_names = df.loc[:, df.columns != target_feature].columns.values
    return X, y, feature_names

def mutual_information(X_Y,X,Y):
    total = 0
    counter = 0
    index = 0
    for i in X_Y:
        if counter == 2:
            index += 1
        total += i*np.log2(i/(X[counter % 2]*Y[index]))
        counter +=1
    return total

In [2]:
X, y, feature_names = load_hugin_dataset("synthetic_v2_1000.dat", 'Label')

In [3]:
from sklearn.feature_selection import chi2, mutual_info_classif

In [4]:
feature_names

array(['F3', 'F2', 'F1'], dtype=object)

In [5]:
F1 = [[i] for i in X[:, 2]]
F2 = [[i] for i in X[:, 1]]
F3 = [[i] for i in X[:, 0]]

# Problem 1

## Part A

In [6]:
F1_ = [.55,.45]
Label = [.50,.50]

In [7]:
Label_F1 = []
Label_F1 += [.5 * .9] 
Label_F1 += [.5 * .2]
Label_F1 += [.5 * .1]
Label_F1 += [.5 * .8]
print(Label_F1, sum(Label_F1))

[0.45, 0.1, 0.05, 0.4] 1.0


In [8]:
mutual_information(Label_F1,Label,F1_)

0.39731260974948646

In [9]:
# Testing
size = 100
example = [[True] if i < int((F1_[0])*size)  else [False] for i in range(size)]
label = ['A' if i < int(Label_F1[0]*size) or i > int(size-(Label_F1[2]*size+1))  else 'B' for i in range(size)]
mutual_info_classif(example, label, discrete_features=True)/np.log(2)

array([0.39731261])

## Part B

In [10]:
mutual_info_classif(F1, y, discrete_features=True)/np.log(2)

array([0.42399351])

# Problem 2

## Part A

In [11]:
F2_ = [.55,.45]

In [12]:
Label_F2 = []
Label_F2 += [.5 * .4] 
Label_F2 += [.5 * .7]
Label_F2 += [.5 * .6]
Label_F2 += [.5 * .3]
print(Label_F2, sum(Label_F2))

[0.2, 0.35, 0.3, 0.15] 1.0


In [13]:
mutual_information(Label_F2,Label,F2_)

0.06665370714512754

In [14]:
#Testing
size = 100
example = [[True] if i < int((F2_[0])*size)  else [False] for i in range(size)]
label = ['A' if i < int(Label_F2[0]*size) or i > int(size-(Label_F2[2]*size+1))  else 'B' for i in range(size)]
mutual_info_classif(example, label, discrete_features=True)/np.log(2)

array([0.06665371])

## Part B

In [15]:
mutual_info_classif(F2, y, discrete_features=True)/np.log(2)

array([0.0571478])

# Problem 3 

## Part A

In [16]:
F3_ = [.545,.455]

In [17]:
Label_F3 = []
Label_F3 += [.5 * .86] 
Label_F3 += [.5 * .23]
Label_F3 += [.5 * .14]
Label_F3 += [.5 * .77]
print(Label_F3, sum(Label_F3))

[0.43, 0.115, 0.07, 0.385] 1.0


In [18]:
mutual_information(Label_F3,Label,F3_)

0.31302411388619616

In [19]:
# Testing
size = 1000
example = [[True] if i < int((F3_[0])*size)  else [False] for i in range(size)]
label = ['A' if i < int(Label_F3[0]*size) or i > int(size-(Label_F3[2]*size+1))  else 'B' for i in range(size)]
mutual_info_classif(example, label, discrete_features=True)/np.log(2)

array([0.31302411])

## Part B

In [20]:
mutual_info_classif(F3, y, discrete_features=True)/np.log(2)

array([0.34144697])

# Problem 4

## Part A

In [21]:
F1_F3_True = [.9587,.0413]
Label_F3_True = [.789,.211]

In [22]:
Label_F1_F3_True = []
Label_F1_F3_True += [.9587 * .8182] 
Label_F1_F3_True += [.9587 * .1818]
Label_F1_F3_True += [.0413 * .1111]
Label_F1_F3_True += [.0413 * .8889]
print(Label_F1_F3_True, sum(Label_F1_F3_True))

[0.78440834, 0.17429166, 0.004588430000000001, 0.036711570000000006] 1.0


In [23]:
mutual_information(Label_F1_F3_True,Label_F3_True,F1_F3_True)

0.06686299074387433

## Part B

In [37]:
indicies = [i for i in range(len(F3)) if F3[i] == [True]]
y_sample = [y[j] for j in indicies]
print(len(y_sample))
x_sample = [F1[k] for k in indicies]
mutual_info_classif(x_sample, y_sample, discrete_features=True)/np.log(2)

566


array([0.0582666])

# Problem 5

## Part A

In [25]:
F1_F3_False = [.0604,.9396]
Label_F3_False = [.1538,.8462]

In [26]:
Label_F1_F3_False = []
Label_F1_F3_False += [.0604 * .8182] 
Label_F1_F3_False += [.0604 * .1818]
Label_F1_F3_False += [.9396 * .1111]
Label_F1_F3_False += [.9396 * .8889]
print(Label_F1_F3_False, sum(Label_F1_F3_False))

[0.04941928, 0.01098072, 0.10438956, 0.83521044] 1.0


In [27]:
mutual_information(Label_F1_F3_False,Label_F3_False,F1_F3_False)

0.10514666759156843

## Part B

In [28]:
indicies = [i for i in range(len(F3)) if F3[i] == [False]]
y_sample = [y[j] for j in indicies]
x_sample = [F1[k] for k in indicies]
mutual_info_classif(x_sample, y_sample, discrete_features=True)/np.log(2)

array([0.11679318])

# Problem 6

## Part A

In [29]:
F3_F1_True = [.95,.05]
Label_F1_True = [.8182,.1818]

In [30]:
Label_F3_F1_True = []
Label_F3_F1_True += [.95 * .8182] 
Label_F3_F1_True += [.95 * .1818]
Label_F3_F1_True += [.05 * .8182]
Label_F3_F1_True += [.05 * .1818]
print(Label_F3_F1_True, sum(Label_F3_F1_True))

[0.77729, 0.17270999999999997, 0.04091, 0.009089999999999999] 1.0


In [31]:
mutual_information(Label_F3_F1_True,Label_F1_True,F3_F1_True)

0.0

## Part B

In [32]:
indicies = [i for i in range(len(F1)) if F1[i] == [True]]
y_sample = [y[j] for j in indicies]
x_sample = [F3[k] for k in indicies]
mutual_info_classif(x_sample, y_sample, discrete_features=True)/np.log(2)

array([0.00103186])

# Problem 7

## Part A

In [33]:
F3_F1_False = [.05,.95]
Label_F1_False = [.1111,.8889]

In [34]:
Label_F3_F1_False = []
Label_F3_F1_False += [.05 * .1111] 
Label_F3_F1_False += [.05 * .8889]
Label_F3_F1_False += [.95 * .1111]
Label_F3_F1_False += [.95 * .8889]
print(Label_F3_F1_False, sum(Label_F3_F1_False))

[0.005555000000000001, 0.044445000000000005, 0.105545, 0.844455] 1.0


In [35]:
mutual_information(Label_F3_F1_False,Label_F1_False,F3_F1_False)

0.0

## Part B

In [36]:
indicies = [i for i in range(len(F1)) if F1[i] == [False]]
y_sample = [y[j] for j in indicies]
x_sample = [F3[k] for k in indicies]
mutual_info_classif(x_sample, y_sample, discrete_features=True)/np.log(2)

array([0.00123679])